//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface XCApplicationMonitor : NSObject
{
    NSMutableDictionary *_applicationImplementations;
    NSMutableDictionary *_applicationProcessesForPID;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedMonitor;
@property NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)terminateApplicationProcess:(id)arg1;
- (id)monitoredApplicationWithProcessIdentifier:(int)arg1;
- (void)_beginMonitoringApplication:(id)arg1;
@property(readonly, copy) NSArray *monitoredApplications;
- (void)setApplicationProcess:(id)arg1 forPID:(int)arg2;
- (id)applicationProcessWithPID:(int)arg1;
- (id)applicationImplementationForApplicationAtPath:(id)arg1 bundleID:(id)arg2;
- (id)init;

@end

