//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebDriverAgentLib/CDStructures.h>
#import <XCTest/XCUIElementAttributes.h>

@class NSArray, NSDictionary, NSString, XCAccessibilityElement, XCUIApplication;

NS_ASSUME_NONNULL_BEGIN

@interface XCElementSnapshot : NSObject <XCUIElementAttributes, NSSecureCoding>
{
    NSString *_identifier;
    id _value;
    NSString *_placeholderValue;
    _Bool _enabled;
    _Bool _selected;
    _Bool _hasFocus;
    _Bool _isMainWindow;
    _Bool _hasKeyboardFocus;
    XCUIApplication *_application;
    unsigned long long _generation;
    NSString *_title;
    NSString *_label;
    unsigned long long _elementType;
    long long _horizontalSizeClass;
    long long _verticalSizeClass;
    XCAccessibilityElement *_accessibilityElement;
    XCAccessibilityElement *_parentAccessibilityElement;
    XCElementSnapshot *_parent;
    NSArray *_children;
    unsigned long long _traits;
    NSArray *_userTestingAttributes;
    NSDictionary *_additionalAttributes;
    struct CGRect _frame;
}

+ (_Bool)supportsSecureCoding;
@property _Bool hasKeyboardFocus; // @synthesize hasKeyboardFocus=_hasKeyboardFocus;
@property(copy, nullable) NSDictionary *additionalAttributes; // @synthesize additionalAttributes=_additionalAttributes;
@property(copy, nullable) NSArray *userTestingAttributes; // @synthesize userTestingAttributes=_userTestingAttributes;
@property unsigned long long traits; // @synthesize traits=_traits;
@property _Bool isMainWindow; // @synthesize isMainWindow=_isMainWindow;
@property(copy, nullable) NSArray *children; // @synthesize children=_children;
@property XCElementSnapshot *parent; // @synthesize parent=_parent;
@property(retain) XCAccessibilityElement *parentAccessibilityElement; // @synthesize parentAccessibilityElement=_parentAccessibilityElement;
@property(retain) XCAccessibilityElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
@property _Bool hasFocus; // @synthesize hasFocus=_hasFocus;
@property(getter=isSelected) _Bool selected; // @synthesize selected=_selected;
@property(getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
//@property unsigned long elementType; // @synthesize elementType=_elementType;
@property(readonly, nullable) NSString *placeholderValue; // @synthesize placeholderValue=_placeholderValue;
@property(readonly, copy) NSString *label; // @synthesize label=_label;
@property(copy) NSString *title; // @synthesize title=_title;
@property(readonly, nullable) id value; // @synthesize value=_value;
@property struct CGRect frame; // @synthesize frame=_frame;
@property(readonly, nullable) NSString *identifier; // @synthesize identifier=_identifier;
- (nullable id)_uniquelyIdentifyingObjectiveCCode;
- (nullable id)_uniquelyIdentifyingSwiftCode;
- (_Bool)_isAncestorOfElement:(nullable id)arg1;
- (_Bool)_isDescendantOfElement:(nullable id)arg1;
@property(readonly, nullable) NSArray *suggestedHitpoints;
- (XCElementSnapshot *)_rootElement;
@property(readonly) struct CGRect visibleFrame;
@property(readonly, nullable) XCElementSnapshot *scrollView;
- (_Bool)_frameFuzzyMatchesElement:(nullable id)arg1;
- (_Bool)_fuzzyMatchesElement:(nullable id)arg1;
- (_Bool)_matchesElement:(nullable id)arg1;
- (NSArray<XCElementSnapshot *> *)_allDescendants;
- (_Bool)hasDescendantMatchingFilter:(nullable CDUnknownBlockType)arg1;
- (NSArray<XCElementSnapshot *> *)descendantsByFilteringWithBlock:(BOOL(^)(XCElementSnapshot *snapshot))block;
- (nullable id)elementSnapshotMatchingAccessibilityElement:(nullable id)arg1;
- (void)enumerateDescendantsUsingBlock:(CDUnknownBlockType _Nullable )arg1;
@property(readonly, copy) NSString *truncatedValueString;
@property(readonly, copy) NSString *compactDescription;
@property(readonly, copy, nullable) NSString *pathDescription;
@property(readonly, nullable) NSString *recursiveDescriptionIncludingAccessibilityElement;
@property(readonly, nullable) NSString *recursiveDescription;
- (nullable id)recursiveDescriptionWithIndent:(nullable id)arg1 includeAccessibilityElement:(_Bool)arg2;
- (nullable id)description;
- (void)encodeWithCoder:(nullable id)arg1;
- (nullable id)initWithCoder:(nullable id)arg1;
@property(readonly, copy, nullable) NSArray *identifiers;
@property(nonatomic) unsigned long long generation; // @synthesize generation=_generation;
@property(nonatomic, nullable) XCUIApplication *application; // @synthesize application=_application;
- (nullable id)init;
- (void)dealloc;

@end


NS_ASSUME_NONNULL_END
