//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCTestSuite.h>

@class NSString;

@interface XCTestSuite (XCTestProbeExtensions)
- (void)removeTestsWithNames:(id)arg1;
@property(copy) NSString *name;
@end

