//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCTestManager_IDEInterface-Protocol.h"

@class XCAXClient_iOS, XCAccessibilityElement, XCApplicationMonitor, XCUIApplicationImpl;

@protocol XCTestManager_IDEInterface;
@protocol XCTRunnerAutomationSession;

@interface XCUIApplicationProcess : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _accessibilityActive;
    unsigned long long _applicationState;
    int _processID;
    id _token;
    _Bool _eventLoopHasIdled;
    _Bool _hasReceivedEventLoopHasIdled;
    _Bool _animationsHaveFinished;
    _Bool _hasReceivedAnimationsHaveFinished;
    XCUIApplicationImpl *_applicationImplementation;
    id <XCTestManager_IDEInterface> _IDEProxy;
    XCApplicationMonitor *_applicationMonitor;
    XCAXClient_iOS *_AXClient_iOS;
}

@property XCAXClient_iOS *AXClient_iOS; // @synthesize AXClient_iOS=_AXClient_iOS;
@property XCApplicationMonitor *applicationMonitor; // @synthesize applicationMonitor=_applicationMonitor;
@property id <XCTestManager_IDEInterface> IDEProxy; // @synthesize IDEProxy=_IDEProxy;
@property XCUIApplicationImpl *applicationImplementation; // @synthesize applicationImplementation=_applicationImplementation;
- (void)terminate;
- (void)waitForQuiescence;
@property _Bool hasReceivedAnimationsHaveFinished;
@property _Bool animationsHaveFinished;
@property _Bool hasReceivedEventLoopHasIdled;
@property _Bool eventLoopHasIdled;
@property(retain) id token;
@property(nonatomic) int processID;
@property(nonatomic) unsigned long long applicationState;
@property(nonatomic) _Bool accessibilityActive;
@property(readonly, copy) XCAccessibilityElement *accessibilityElement;
- (id)description;
- (id)init;
- (id)initWithApplicationMonitor:(id)arg1 AXInterface:(id)arg2 IDEProxy:(id)arg3;
- (void)dealloc;

@end

