//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCUIRemote.h>

@interface XCUIRemote ()
{
}

+ (instancetype)sharedRemote;
- (void)_silentlyPressButton:(XCUIRemoteButton)arg1 forDuration:(NSTimeInterval)arg2;
- (void)_dispatchEventWithPage:(unsigned int)arg1 usage:(unsigned int)arg2 duration:(double)arg3;

@end

