//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCUIElement.h>

@class NSString, XCElementSnapshot, XCUIApplication, XCUIElementQuery;

@interface XCUIElement ()
{
    _Bool _safeQueryResolutionEnabled;
    XCUIElementQuery *_query;
    XCElementSnapshot *_lastSnapshot;
}

@property _Bool safeQueryResolutionEnabled; // @synthesize safeQueryResolutionEnabled=_safeQueryResolutionEnabled;
@property(retain) XCElementSnapshot *lastSnapshot; // @synthesize lastSnapshot=_lastSnapshot;
@property(readonly) XCUIElementQuery *query; // @synthesize query=_query;
@property(readonly, nonatomic) long long interfaceOrientation;
@property(readonly) _Bool hasKeyboardFocus;
- (unsigned long long)traits;
- (void)resolveHandleUIInterruption:(_Bool)arg1;
- (void)resolve;
@property(readonly, nonatomic) XCUIApplication *application;
- (id)description;
- (id)initWithElementQuery:(id)arg1;
- (void)dealloc;

@end


