//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;


@protocol XCUIElementAttributes
@property(readonly) _Bool hasFocus;
@property(readonly, getter=isSelected) _Bool selected;
@property(readonly) NSString *placeholderValue;
@property(readonly) long long verticalSizeClass;
@property(readonly) long long horizontalSizeClass;
@property(readonly, getter=isEnabled) _Bool enabled;
@property(readonly) unsigned long long elementType;
@property(readonly, copy) NSString *label;
@property(readonly, copy) NSString *title;
@property(readonly) id value;
@property(readonly) struct CGRect frame;
@property(readonly) NSString *identifier;
@end

