//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UIASyntheticEvents;

@interface UIAHardwareKeyboard : NSObject
{
    UIASyntheticEvents *_eventGenerator;
    unsigned int _modifierState;
}

+ (id)sharedHardwareKeyboard;
@property unsigned int modifierState; // @synthesize modifierState=_modifierState;
@property(readonly) UIASyntheticEvents *eventGenerator; // @synthesize eventGenerator=_eventGenerator;
- (id)deleteForwardKeyCode;
- (id)deleteBackwardKeyCode;
- (id)enterKeyCode;
- (id)upArrowKeyCode;
- (id)downArrowKeyCode;
- (id)rightArrowKeyCode;
- (id)leftArrowKeyCode;
- (void)capsLockKeyUp;
- (void)capsLockKeyDown;
- (void)shiftKeyUp;
- (void)shiftKeyDown;
- (void)controlKeyUp;
- (void)controlKeyDown;
- (void)commandKeyUp;
- (void)commandKeyDown;
- (void)optionKeyUp;
- (void)optionKeyDown;
- (void)keyUpWithKeyCode:(unsigned int)arg1;
- (void)keyUpWithString:(id)arg1;
- (void)keyDownWithKeyCode:(unsigned int)arg1;
- (void)keyDownWithString:(id)arg1;
- (void)pressKeyWithKeyCode:(unsigned int)arg1;
- (void)pressKeyWithString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

