//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIAElement.h>

@interface UIANavigationBar : UIAElement
{
}

+ (id)toOneRelationshipKeys;
+ (id)_moreToOneRelationshipKeys;
- (id)elements;
- (_Bool)_navBarShouldAcceptAXElement:(id)arg1;
- (id)rightButton;
- (id)leftButton;
- (id)name;

@end

