//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAXElement-Protocol.h"

@interface UIAXElement : NSObject <UIAXElement>
{
    struct __AXUIElement *_axuiElementRef;
    double _creationTime;
    double _lastAccessedTime;
    _Bool _isValid;
    int _axError;
}

+ (struct CGRect)_convertHostedViewFrame:(struct CGRect)arg1 forContextID:(id)arg2;
+ (struct CGPoint)_convertHostedCoordinates:(struct CGPoint)arg1 forContextID:(id)arg2;
+ (struct CGRect)_convertRectFromScreenToDevice:(struct CGRect)arg1;
+ (struct CGRect)_convertRectFromDeviceToScreen:(struct CGRect)arg1;
+ (struct CGPoint)_convertPointFromScreenToDevice:(struct CGPoint)arg1;
+ (struct CGPoint)_convertPointFromDeviceToScreen:(struct CGPoint)arg1;
+ (id)stringForTraits:(unsigned long long)arg1;
+ (id)stringForAXNotification:(int)arg1;
+ (id)stringForAXError:(int)arg1;
+ (id)uiaxAccessibilityUIServerElement;
+ (id)uiaxFocusedApplicationElement;
+ (id)uiaxSpringBoardElement;
+ (id)uiaxSystemApplicationElement;
+ (id)uiaxSystemWideElement;
+ (id)uiaxElementAtPosition:(struct CGPoint)arg1;
+ (id)uiaxApplicationAtPosition:(struct CGPoint)arg1;
+ (id)_objectForCFTypeRef:(void *)arg1;
+ (int)_parameterizedAttributeForString:(id)arg1;
+ (id)_stringForParameterizedAttribute:(int)arg1;
+ (int)_attributeForString:(id)arg1;
+ (id)_stringForAttribute:(int)arg1;
+ (id)_stringsForTraitsDictionary;
+ (id)_parameterizedAttributesForStringsDictionary;
+ (id)_stringsForParameterizedAttributesDictionary;
+ (id)_regularAttributesForStringsDictionary;
+ (id)_stringsForRegularAttributesDictionary;
+ (id)_traitStrings;
+ (id)_traitNumbers;
+ (id)_parameterizedAttributeStrings;
+ (id)_parameterizedAttributeNumbers;
+ (id)_regularAttributeStrings;
+ (id)_regularAttributeNumbers;
+ (id)uiaxElementWithAXUIElementRef:(struct __AXUIElement *)arg1;
+ (_Bool)unregisterObserver:(void *)arg1 forAXNotification:(int)arg2;
+ (_Bool)registerObserver:(void *)arg1 forAXNotification:(int)arg2;
+ (_Bool)registerObserver:(void *)arg1 forAXNotifications:(_Bool)arg2;
+ (void)_raiseIfAXErrorAPIDisabled:(int)arg1;
+ (void)_raiseAXErrorAPIDisabled;
+ (void)initializeAccessibility;
+ (void)initialize;
- (void)logAXTree;
- (void)logAXAncestry;
- (void)logAXInfo;
- (_Bool)_hasNonzeroFrame;
- (id)ancestry;
- (id)descendantWithTestingTrait:(id)arg1;
- (id)descendantsWithAttributes:(id)arg1 traits:(unsigned long long)arg2;
- (id)descendants;
- (id)childWithTestingTrait:(id)arg1;
- (id)children;
- (id)responder;
- (id)parent;
- (id)firstElementOfAttribute:(int)arg1 withValue:(id)arg2 forAttribute:(int)arg3;
- (id)uiaxElementAtCenterPoint;
- (id)centerPoint;
- (id)hitpoint;
- (_Bool)_isVisibleAtPoint:(struct CGPoint)arg1;
- (id)rect;
- (id)description;
- (unsigned long long)traits;
- (id)traitsNumber;
- (id)_copyTraitsNumber;
- (id)stringForAllKnownAttributes;
- (id)stringForAttributes:(id)arg1;
- (id)valuesForAllKnownAttributes;
- (_Bool)checkIsValid;
- (_Bool)isValid;
- (int)axError;
- (int)pid;
- (_Bool)performAXAction:(int)arg1 withValue:(id)arg2;
- (_Bool)performAXAction:(int)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (id)valueForKey:(id)arg1;
- (id)valueForAttribute:(int)arg1 parameter:(id)arg2;
- (id)valuesForAttributes:(id)arg1;
- (_Bool)setValue:(id)arg1 forAttribute:(int)arg2;
- (id)valueForAttribute:(int)arg1;
- (struct __AXUIElement *)axuiElementRef;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (void)_setLastAccessedTime:(double)arg1;
- (double)_lastAccessedTime;
- (double)_creationTime;
- (id)_initWithAXUIElementRef:(struct __AXUIElement *)arg1;
- (void)_setValidForAXError:(int)arg1;
- (void)_invalidate;

@end

