//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCTestExpectation.h>

@class NSPredicate, NSTimer;

@interface _XCPredicateExpectation : XCTestExpectation
{
    id _object;
    NSPredicate *_predicate;
    CDUnknownBlockType _handler;
    NSTimer *_timer;
}
@property(copy) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(copy) NSPredicate *predicate; // @synthesize predicate=_predicate;
@property(retain) id object; // @synthesize object=_object;

- (void)_considerFulfilling;
- (void)cleanup;
- (void)setTimer:(id)arg1;
- (void)startObserving;

@end
