//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface _XCTestExpectationWaiterImplementation : NSObject
{
    id <XCTestExpectationWaiterDelegate> _delegate;
    NSString *_name;
    NSArray *_waitCallStackReturnAddresses;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSArray *_expectations;
    struct __CFRunLoop *_waitingRunLoop;
    long long _state;
    double _timeout;
    long long _result;
    BOOL _enforceOrderOfFulfillment;
}
@property BOOL enforceOrderOfFulfillment; // @synthesize enforceOrderOfFulfillment=_enforceOrderOfFulfillment;
@property long long result; // @synthesize result=_result;
@property long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSArray *expectations; // @synthesize expectations=_expectations;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy) NSString *name; // @synthesize name=_name;
@property id <XCTestExpectationWaiterDelegate> delegate; // @synthesize delegate=_delegate;
@property double timeout; // @synthesize timeout=_timeout;
@property struct __CFRunLoop *waitingRunLoop; // @synthesize waitingRunLoop=_waitingRunLoop;
@property(copy) NSArray *waitCallStackReturnAddresses; // @synthesize waitCallStackReturnAddresses=_waitCallStackReturnAddresses;

- (id)init;

@end
