// Copyright 2004-present Facebook. All Rights Reserved.

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, XCTestCase;

@interface _XCTestExpectationImplementation : NSObject
{
    _Bool _hasCompleted;
    XCTestCase *_testCase;
    NSString *_expectationDescription;
}

@property (atomic, copy) NSString *expectationDescription;
@property (atomic, assign) XCTestCase *testCase; // @synthesize testCase=_testCase;
@property (atomic, assign) _Bool hasCompleted; // @synthesize hasCompleted=_hasCompleted;
- (void)dealloc;

@end
