//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebDriverAgentLib/XCElementSnapshot.h>

@interface XCElementSnapshot (Hitpoint)
@property(readonly) CGPoint hitPointForScrolling;
@property(readonly) CGPoint hitPoint;

- (id)hitTest:(struct CGPoint)arg1;

@end
