// Copyright 2004-present Facebook. All Rights Reserved.

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCEventGenerator : NSObject
{
    NSObject<OS_dispatch_queue> *_eventQueue;
    struct __CFRunLoopObserver *_generationObserver;
    unsigned long long _generation;
}

+ (id)sharedGenerator;
@property (atomic, assign) unsigned long long generation; // @synthesize generation=_generation;
@property (atomic, readonly) NSObject<OS_dispatch_queue> *eventQueue;
- (double)rotateInRect:(CGRect)arg1 withRotation:(double)arg2 velocity:(double)arg3 orientation:(long long)arg4 handler:(CDUnknownBlockType)arg5;
- (double)pinchInRect:(CGRect)arg1 withScale:(double)arg2 velocity:(double)arg3 orientation:(long long)arg4 handler:(CDUnknownBlockType)arg5;
- (double)pressAtPoint:(CGPoint)arg1 forDuration:(double)arg2 liftAtPoint:(CGPoint)arg3 velocity:(double)arg4 orientation:(long long)arg5 name:(id)arg6 handler:(CDUnknownBlockType)arg7;
- (double)pressAtPoint:(CGPoint)arg1 forDuration:(double)arg2 orientation:(long long)arg3 handler:(CDUnknownBlockType)arg4;
- (double)tapWithNumberOfTaps:(unsigned long long)arg1 numberOfTouches:(unsigned long long)arg2 inRect:(CGRect)arg3 orientation:(long long)arg4 handler:(CDUnknownBlockType)arg5;
- (double)twoFingerTapInRect:(CGRect)arg1 orientation:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (double)doubleTapAtPoint:(CGPoint)arg1 orientation:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (double)tapAtPoint:(CGPoint)arg1 orientation:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (void)_startEventSequenceWithSteppingCallback:(CDUnknownBlockType)arg1;
- (void)_scheduleCallback:(CDUnknownBlockType)arg1 afterInterval:(double)arg2;
- (id)init;

@end
