//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class _XCTestExpectationImplementation;

@interface XCTestExpectation : NSObject
{
    id _internalImplementation;
}
@property(readonly) _XCTestExpectationImplementation *internalImplementation; // @synthesize internalImplementation=_internalImplementation;

+ (id)expectationForTestCase:(id)arg1 withDescription:(id)arg2;

- (void)cleanup;
- (void)fulfill;
- (id)_initForTestCase:(id)arg1 withDescription:(id)arg2;

@end
