// Copyright 2004-present Facebook. All Rights Reserved.

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTWebDriverAgentLib/XCTest.h>

@class NSString;

@interface XCTest (ReportingAdditions)
@property (atomic, copy, readonly) NSString *_methodNameForReporting;
@property (atomic, copy, readonly) NSString *_classNameForReporting;
@end
