// Copyright 2004-present Facebook. All Rights Reserved.

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMutableArray;

@interface XCTouchPath : NSObject <NSSecureCoding>
{
    NSMutableArray *_touchEvents;
    _Bool _immutable;
    unsigned long long _index;
    long long _interfaceOrientation;
}

+ (_Bool)supportsSecureCoding;
@property (atomic, readonly) long long interfaceOrientation;
@property (atomic, assign) unsigned long long index; // @synthesize index=_index;
@property (atomic, assign) _Bool immutable; // @synthesize immutable=_immutable;
- (id)description;
- (id)firstEventAfterOffset:(double)arg1;
- (id)lastEventBeforeOffset:(double)arg1;
@property (atomic, readonly) _Bool complete;
- (void)_addTouchEvent:(id)arg1;
- (void)liftUpAtPoint:(struct CGPoint)arg1 offset:(double)arg2;
- (void)moveToPoint:(struct CGPoint)arg1 atOffset:(double)arg2;
@property (atomic, copy, readonly) NSArray *touchEvents;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTouchDown:(struct CGPoint)arg1 orientation:(long long)arg2 offset:(double)arg3;
- (id)init;
- (void)dealloc;

@end
