//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMutableArray, NSString;

@interface XCTouchGesture : NSObject <NSSecureCoding>
{
    NSMutableArray *_touchPaths;
    BOOL _immutable;
    NSString *_name;
}
@property BOOL immutable; // @synthesize immutable=_immutable;
@property(readonly, copy) NSString *name; // @synthesize name=_name;
@property(readonly) double maximumOffset;
@property(readonly) NSArray *touchPaths;

- (void)makeImmutable;
- (void)addTouchPath:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)init;

@end
