// Copyright 2004-present Facebook. All Rights Reserved.

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, NSUUID;

@interface XCUIElementAsynchronousHandlerWrapper : NSObject
{
    CDUnknownBlockType _handler;
    NSString *_handlerDescription;
    NSUUID *_identifier;
}

@property (atomic, copy) NSUUID *identifier;
@property (atomic, copy) NSString *handlerDescription;
@property (atomic, copy) CDUnknownBlockType handler;
- (void)dealloc;

@end
