//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TargetConditionals.h>

#if TARGET_OS_IPHONE

// TODO tvos
@interface XCUIRemote : NSObject
{
}

+ (id)sharedRemote;
- (void)_silentlyPressButton:(unsigned long long)arg1 forDuration:(double)arg2;
- (void)pressButton:(unsigned long long)arg1 forDuration:(double)arg2;
- (void)pressButton:(unsigned long long)arg1;
- (void)_dispatchEventWithPage:(unsigned int)arg1 usage:(unsigned int)arg2 duration:(double)arg3;

@end

#endif
