//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TargetConditionals.h>

#import <XCTest/XCUIElement.h>

#if !TARGET_OS_IPHONE

@interface XCUIElement (XCUIElementTypePickerWheel)
- (void)adjustToPickerWheelValue:(id)arg1;
@end

#endif
