//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAElement.h"

@class NSString, UIAElementArray, UIAKeyboard;

@interface UIAApplication : UIAElement
{
    UIAElementArray *_windows;
    NSString *_name;
    NSString *_bundleID;
    NSString *_bundlePath;
    NSString *_axBundlePath;
    NSString *_version;
    NSString *_bundleVersion;
    const void *_privateRef;
}

+ (id)toManyRelationshipKeys;
+ (id)toOneRelationshipKeys;
+ (id)attributeKeys;
- (id)scriptingSynonymStrings;
- (id)toolbar;
- (id)tabBar;
- (id)navigationBar;
- (id)appIconScrollView;
- (id)appItemScrollView;
- (id)_scrollViewWithElementType:(id)arg1;
- (id)editingMenu;
- (id)statusBar;
- (id)alert;
- (id)activityView;
- (id)actionSheet;
- (UIAKeyboard *)keyboard;
- (id)mainWindow;
- (id)_axMainWindow;
- (id)keyWindow;
- (id)windows;
- (id)interfaceOrientation;
- (id)preferencesValueForKey:(id)arg1;
- (void)setPreferencesValue:(id)arg1 forKey:(id)arg2;
- (id)isCameraIrisOpen;
- (id)isVisible;
- (id)bundleVersion;
- (id)version;
- (id)localizedStringForKey:(id)arg1 withOptions:(id)arg2;
- (id)localizedStringForKey:(id)arg1;
- (id)_axBundle;
- (id)_axBundlePath;
- (id)_bundle;
- (id)bundlePath;
- (id)_bundlePath;
- (id)stateDescription;
- (unsigned int)_state;
- (id)name;
- (id)_name;
- (id)bundleID;
- (id)_bundleID;
- (_Bool)_isSystemApplication;
- (void)_invalidate;
- (void)dealloc;
- (id)init;

@end

