//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAElement.h"

@interface UIAKeyboard : UIAElement
{
    double _interKeyDelay;
    double _interKeyDelayVariance;
}

@property double interKeyDelayVariance; // @synthesize interKeyDelayVariance=_interKeyDelayVariance;
@property double interKeyDelay; // @synthesize interKeyDelay=_interKeyDelay;
- (void)triggerDictationFromAudioInputPath:(id)arg1;
- (void)typeString:(id)arg1;
- (void)_typeKeyForString:(id)arg1 keyLayout:(id)arg2;
- (void)_delayForTyping;
- (id)inputMode;
- (id)init;

@end

