//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIAElement.h>

@interface UIAPageIndicator : UIAElement
{
}

- (void)selectPage:(id)arg1;
- (void)goToPreviousPage;
- (void)goToNextPage;
- (_Bool)_flipPages:(int)arg1;
- (id)pageCount;
- (id)pageIndex;

@end

