//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIAElement.h>

@class UIScreen;

@interface UIAScreen : UIAElement
{
    UIScreen *_uiScreen;
}

+ (id)attributeKeys;
- (id)uiScreen;
- (void)setBrightness:(id)arg1;
- (id)brightness;
- (id)_uiaApplicationFrame;
- (id)applicationFrame;
- (id)scale;
- (id)bounds;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)_uiScreen;
- (void)dealloc;
- (id)_initWithUIScreen:(id)arg1 parent:(id)arg2;

@end

