
#import <Foundation/Foundation.h>

/**
 An alert generated by the OS that can be dismissed automatically by accepting
 or declining.  A request for access to the camera, to use your location, or
 that there is no SIM card installed are all examples of alerts that are
 generated by the OS.
 */
@interface CBXSpringBoardAlert : NSObject

/**
 * The mark of the button that should be used to dismiss the alert.
 */
@property(copy, readonly) NSString *defaultDismissButtonMark;

/**
 Should this alert be dismissed by accept or declining? Sometimes, the default
 dimiss button is not correct because it changed after an iOS update.  If that
 is the case, the default accept/decline buttons will be used.
 */
@property(assign, readonly) BOOL shouldAccept;

/**
 Returns a new instance of SpringBoardAlert.

 @param alertTitleFragment A portion of an alert title that can be used to
 match against an alert title.
 @param dismissButtonTitle The title of the button that should be touched to
 dismiss the alert.
 @param shouldAccept Should this alert be dismissed by accepting or
 declining?  This is used when the default dismiss button title is not
 present - most likely because it changed after on iOS update.

 @return SpringBoardAlert instance
 */
- (instancetype)initWithAlertTitleFragment:(NSString *)alertTitleFragment
                        dismissButtonTitle:(NSString *)dismissButtonTitle
                              shouldAccept:(BOOL)shouldAccept;

/**
 Does the alertTitle match this instance?

 @param alertTitle The full title (label) of the alert.

 @return YES if there is a match, no otherwise.
 */
- (BOOL)matchesAlertTitle:(NSString *)alertTitle;

@end
