/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDate, XCTest;

@interface _XCInternalTestRun : NSObject
{
    XCTest *_test;
    double _startTimeInterval;
    double _stopTimeInterval;
    unsigned long long _executionCount;
    unsigned long long _failureCount;
    unsigned long long _unexpectedExceptionCount;
    _Bool _hasStarted;
    _Bool _hasStopped;
}

@property (atomic, readonly) _Bool hasStopped;
@property (atomic, readonly) XCTest *test;
- (void)recordFailureWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3 expected:(_Bool)arg4;
@property (atomic, readonly) unsigned long long testCaseCount;
@property (atomic, readonly) unsigned long long unexpectedExceptionCount;
@property (atomic, readonly) unsigned long long failureCount;
@property (atomic, readonly) unsigned long long executionCount;
- (void)stop;
- (void)start;
@property (atomic, copy, readonly) NSDate *stopDate;
@property (atomic, copy, readonly) NSDate *startDate;
@property (atomic, readonly) double testDuration;
@property (atomic, readonly) double totalDuration;
- (id)initWithTest:(id)arg1;
- (void)dealloc;

@end
