/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSInvocation, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_source>, NSString, XCTestCaseRun, XCTestContext;

@interface _XCTestCaseImplementation : NSObject
{
    NSInvocation *_invocation;
    XCTestCaseRun *_testCaseRun;
    _Bool _continueAfterFailure;
    NSMutableSet *_expectations;
    NSMutableArray *_fulfillments;
    NSObject<OS_dispatch_source> *_timeoutSource;
    double _timeoutDuration;
    _Bool _waiting;
    CDUnknownBlockType _completionHandler;
    NSArray *_performanceMetricIDs;
    NSArray *_activePerformanceMetricIDs;
    NSMutableDictionary *_perfMetricDataForID;
    unsigned long long _startWallClockTime;
    struct time_value _startUserTime;
    struct time_value _startSystemTime;
    unsigned long long _measuringIteration;
    _Bool _isMeasuringMetrics;
    _Bool _didMeasureMetrics;
    _Bool _didStartMeasuring;
    _Bool _didStopMeasuring;
    NSString *_filePathForUnexpectedFailure;
    unsigned long long _lineNumberForUnexpectedFailure;
    unsigned long long _callAddressForCurrentWait;
    NSArray *_callAddressesForLastCreatedExpectation;
    long long _runLoopNestingCount;
    NSMutableArray *_failureRecords;
    _Bool _shouldHaltWhenReceivesControl;
    _Bool _shouldIgnoreSubsequentFailures;
    NSMutableArray *_activityRecordStack;
    XCTestContext *_testContext;
}

@property (atomic, readonly) XCTestContext *testContext;
@property (retain, nonatomic) NSMutableArray *activityRecordStack;
@property (atomic, assign) _Bool shouldIgnoreSubsequentFailures; // @synthesize shouldIgnoreSubsequentFailures=_shouldIgnoreSubsequentFailures;
@property (atomic, assign) _Bool shouldHaltWhenReceivesControl; // @synthesize shouldHaltWhenReceivesControl=_shouldHaltWhenReceivesControl;
@property (retain, nonatomic) NSMutableArray *failureRecords;
@property (atomic, assign) long long runLoopNestingCount; // @synthesize runLoopNestingCount=_runLoopNestingCount;
@property (nonatomic, assign) NSObject<OS_dispatch_source> *timeoutSource;
@property (atomic, copy) NSArray *callAddressesForLastCreatedExpectation;
@property (atomic, assign) unsigned long long callAddressForCurrentWait; // @synthesize callAddressForCurrentWait=_callAddressForCurrentWait;
@property (atomic, assign) unsigned long long lineNumberForUnexpectedFailure; // @synthesize lineNumberForUnexpectedFailure=_lineNumberForUnexpectedFailure;
@property (atomic, copy) NSString *filePathForUnexpectedFailure;
@property (atomic, copy) CDUnknownBlockType completionHandler;
@property (atomic, assign) double timeoutDuration; // @synthesize timeoutDuration=_timeoutDuration;
@property (atomic, assign) _Bool waiting; // @synthesize waiting=_waiting;
@property (retain, nonatomic) NSMutableArray *fulfillments;
@property (retain, nonatomic) NSMutableSet *expectations;
@property (atomic, assign) _Bool didStopMeasuring; // @synthesize didStopMeasuring=_didStopMeasuring;
@property (atomic, assign) _Bool didStartMeasuring; // @synthesize didStartMeasuring=_didStartMeasuring;
@property (atomic, assign) _Bool didMeasureMetrics; // @synthesize didMeasureMetrics=_didMeasureMetrics;
@property (atomic, assign) _Bool isMeasuringMetrics; // @synthesize isMeasuringMetrics=_isMeasuringMetrics;
@property (atomic, assign) unsigned long long measuringIteration; // @synthesize measuringIteration=_measuringIteration;
@property (atomic, assign) struct time_value startUserTime; // @synthesize startUserTime=_startUserTime;
@property (atomic, assign) struct time_value startSystemTime; // @synthesize startSystemTime=_startSystemTime;
@property (atomic, assign) unsigned long long startWallClockTime; // @synthesize startWallClockTime=_startWallClockTime;
@property (atomic, retain) NSMutableDictionary *perfMetricDataForID;
@property (atomic, copy) NSArray *activePerformanceMetricIDs;
@property (atomic, copy) NSArray *performanceMetricIDs;
@property (atomic, assign) _Bool continueAfterFailure; // @synthesize continueAfterFailure=_continueAfterFailure;
@property (atomic, retain) XCTestCaseRun *testCaseRun;
@property (atomic, retain) NSInvocation *invocation;
- (void)resetExpectations;
- (void)addExpectation:(id)arg1;
- (id)init;
- (void)dealloc;

@end
