/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSMutableSet;

@interface _XCTestObservationCenterImplementation : NSObject
{
    NSMutableSet *_observers;
    _Bool _suspended;
}

@property (atomic, assign) _Bool suspended; // @synthesize suspended=_suspended;
@property (atomic, retain) NSMutableSet *observers;
- (id)init;

@end
