/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTWebDriverAgentLib/XCTestObservation.h>

@class NSArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface XCApplicationMonitor : NSObject <XCTestObservation>
{
    NSMutableDictionary *_launchSessionTokens;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedMonitor;
@property (atomic, assign) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property (atomic, copy, readonly) NSArray *allMonitoredApplications;
- (void)testCaseWillStart:(id)arg1;
- (id)monitoredApplicationWithProcessIdentifier:(int)arg1;
- (id)launchSessionTokenForApplication:(id)arg1;
- (void)setLaunchSessionToken:(id)arg1 forApplication:(id)arg2;
- (void)applicationWithBundleID:(id)arg1 didUpdatePID:(int)arg2 andState:(unsigned long long)arg3;
- (void)setAccessibilityActive:(_Bool)arg1 forApplicationWithPID:(int)arg2;
- (void)beginMonitoringApplication:(id)arg1;
- (id)init;

// Remaining properties
@property (atomic, copy, readonly) NSString *debugDescription;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;

@end
