/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTWebDriverAgentLib/XCElementSnapshot.h>

@interface XCElementSnapshot (Hitpoint)
@property (atomic, readonly) CGPoint hitPointForScrolling;
@property (atomic, readonly) CGPoint hitPoint;
- (id)hitTest:(CGPoint)arg1;
@end
