/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTWebDriverAgentLib/XCElementAttributesPrivate.h>
#import <XCTWebDriverAgentLib/CDStructures.h>

@class NSArray, NSDictionary, NSString, XCAccessibilityElement, XCUIApplication;

@interface XCElementSnapshot : NSObject <XCElementAttributesPrivate, NSSecureCoding>
{
    NSString *_identifier;
    id _value;
    NSString *_placeholderValue;
    BOOL _enabled;
    BOOL _selected;
    BOOL _isMainWindow;
    BOOL _hasKeyboardFocus;
    XCUIApplication *_application;
    unsigned long long _generation;
    NSString *_title;
    NSString *_label;
    unsigned long long _elementType;
    long long _horizontalSizeClass;
    long long _verticalSizeClass;
    XCAccessibilityElement *_accessibilityElement;
    XCAccessibilityElement *_parentAccessibilityElement;
    XCElementSnapshot *_parent;
    NSArray *_children;
    unsigned long long _traits;
    NSArray *_userTestingAttributes;
    NSDictionary *_additionalAttributes;
    CGRect _frame;
}
@property (atomic, assign) BOOL hasKeyboardFocus; // @synthesize hasKeyboardFocus=_hasKeyboardFocus;
@property (atomic, copy) NSDictionary *additionalAttributes;
@property (atomic, copy) NSArray *userTestingAttributes;
@property (atomic, assign) unsigned long long traits; // @synthesize traits=_traits;
@property (atomic, assign) BOOL isMainWindow; // @synthesize isMainWindow=_isMainWindow;
@property (atomic, copy) NSArray *children;
@property (atomic, assign) XCElementSnapshot *parent; // @synthesize parent=_parent;
@property (atomic, retain) XCAccessibilityElement *parentAccessibilityElement;
@property (atomic, retain) XCAccessibilityElement *accessibilityElement;
@property (atomic, copy, readonly) NSArray *suggestedHitpoints;
@property (atomic, readonly) CGRect visibleFrame;
@property (atomic, readonly) XCElementSnapshot *scrollView;
@property (atomic, copy, readonly) NSString *truncatedValueString;
@property (atomic, copy, readonly) NSString *compactDescription;
@property (atomic, copy, readonly) NSString *pathDescription;
@property (atomic, copy, readonly) NSString *recursiveDescriptionIncludingAccessibilityElement;
@property (atomic, copy, readonly) NSString *recursiveDescription;
@property (atomic, copy, readonly) NSArray *identifiers;
@property (nonatomic, assign) unsigned long long generation;
@property (nonatomic, assign) XCUIApplication *application;

- (id)init;

- (XCElementSnapshot *)_rootElement;

- (BOOL)_isAncestorOfElement:(XCElementSnapshot *)element;
- (BOOL)_isDescendantOfElement:(XCElementSnapshot *)element;
- (BOOL)_frameFuzzyMatchesElement:(id)arg1;
- (BOOL)_fuzzyMatchesElement:(id)arg1;
- (BOOL)_matchesElement:(id)arg1;
- (BOOL)hasDescendantMatchingFilter:(CDUnknownBlockType)arg1;
- (void)enumerateDescendantsUsingBlock:(void(^)(XCElementSnapshot *))arg1;

- (NSArray<XCElementSnapshot *> *)_allDescendants;
- (NSArray<XCElementSnapshot *> *)descendantsByFilteringWithBlock:(CDUnknownBlockType)arg1;

- (id)recursiveDescriptionWithIndent:(id)arg1 includeAccessibilityElement:(BOOL)arg2;

@end
