/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, XCKeyboardKeyMap;

@interface XCKeyboardInputSolver : NSObject <NSCopying>
{
    XCKeyboardKeyMap *_keyMap;
    NSString *_string;
    unsigned long long _requiredFlags;
    unsigned long long _excludedFlags;
    unsigned long long _currentFlags;
    _Bool _includeModifierKeys;
    struct _NSRange _unsolvedRange;
    NSMutableArray *_solvedInputs;
    NSMutableDictionary *_solvingPaths;
}

@property (atomic, copy, readonly) NSArray *solvedInputs;
@property (atomic, readonly) struct _NSRange unsolvedRange;
@property (atomic, assign) _Bool includeModifierKeys; // @synthesize includeModifierKeys=_includeModifierKeys;
@property (atomic, assign) unsigned long long currentFlags; // @synthesize currentFlags=_currentFlags;
@property (atomic, assign) unsigned long long excludedFlags; // @synthesize excludedFlags=_excludedFlags;
@property (atomic, assign) unsigned long long requiredFlags; // @synthesize requiredFlags=_requiredFlags;
@property (atomic, copy, readonly) NSString *string;
@property (atomic, readonly) XCKeyboardKeyMap *keyMap;
- (id)_solve;
- (id)solve;
- (void)solveWithSolutionRange:(struct _NSRange)arg1 results:(id)arg2;
- (id)extractCompletePathsWithSolutionRange:(struct _NSRange)arg1;
- (unsigned long long)advancePaths;
- (void)advancePath:(id)arg1 range:(id)arg2;
@property (atomic, readonly, getter=isComplete) _Bool complete;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithKeyMap:(id)arg1 string:(id)arg2;
- (id)init;

@end
