/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSSet, NSString;

@interface XCKeyMappingPath : NSObject <NSCopying>
{
    unsigned long long _keyState;
    XCKeyMappingPath *_next;
    NSSet *_inputs;
    NSString *_output;
    unsigned long long _length;
    NSString *_producedString;
}

+ (id)pathWithKeyState:(unsigned long long)arg1 next:(id)arg2 inputs:(id)arg3 output:(id)arg4;
+ (id)emptyPath;
@property (atomic, copy, readonly) NSString *producedString;
@property (atomic, readonly) unsigned long long length;
@property (atomic, copy, readonly) NSString *output;
@property (atomic, copy, readonly) NSSet *inputs;
@property (atomic, copy, readonly) XCKeyMappingPath *next;
@property (atomic, readonly) unsigned long long keyState;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)inputSequenceWithRequiredFlags:(unsigned long long)arg1 excludedFlags:(unsigned long long)arg2;
- (id)inputWithRequiredFlags:(unsigned long long)arg1 excludedFlags:(unsigned long long)arg2;
@property (atomic, readonly, getter=isEmpty) _Bool empty;
@property (atomic, readonly, getter=isComplete) _Bool complete;
- (void)dealloc;
- (id)initWithKeyState:(unsigned long long)arg1 next:(id)arg2 inputs:(id)arg3 output:(id)arg4;
- (id)init;

@end
