/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTWebDriverAgentLib/CDStructures.h>
#import <XCTWebDriverAgentLib/XCTestDriverInterface.h>
#import <XCTWebDriverAgentLib/XCTestManager_TestsInterface.h>
#import <XCTWebDriverAgentLib/XCTestManager_IDEInterface.h>
#import <XCTWebDriverAgentLib/XCTestManager_ManagerInterface.h>

@class DTXConnection, NSString, NSUUID, NSXPCConnection, XCTestConfiguration, XCTestSuite;

@interface XCTestDriver : NSObject <XCTestManager_TestsInterface, XCTestDriverInterface>
{
    XCTestSuite *_currentTestSuite;
    XCTestConfiguration *_currentTestConfiguration;
    CDUnknownBlockType _completionHandler;
    NSXPCConnection *_managerConnection;
    _Bool _connectionInProgress;
    _Bool _waitingToStart;
    _Bool _hasIDEConnection;
    _Bool _runningSuite;
    NSObject<OS_dispatch_queue> *_managerQueue;
    NSUUID *_sessionIdentifier;
    NSString *_sessionSocketPath;
    DTXConnection *_IDEConnection;
    id<XCTestManager_IDEInterface> _IDEProxy;
    long long _IDEProtocolVersion;
    unsigned long long _daemonProtocolVersion;
    int _daemonAvailabilityToken;
}

+ (instancetype)sharedTestDriver;
@property (atomic, assign) unsigned long long daemonProtocolVersion; // @synthesize daemonProtocolVersion=_daemonProtocolVersion;
@property (atomic, assign) _Bool hasIDEConnection; // @synthesize hasIDEConnection=_hasIDEConnection;
@property (atomic, assign) _Bool waitingToStart; // @synthesize waitingToStart=_waitingToStart;
@property (atomic, assign) long long IDEProtocolVersion; // @synthesize IDEProtocolVersion=_IDEProtocolVersion;
@property (atomic, readonly) id<XCTestManager_IDEInterface> IDEProxy;
@property (atomic, readonly) id<XCTestManager_ManagerInterface> managerProxy;
@property (atomic, retain) DTXConnection *IDEConnection;
@property (atomic, retain) NSUUID *sessionIdentifier;
@property (atomic, assign) XCTestSuite *currentTestSuite; // @synthesize currentTestSuite=_currentTestSuite;
- (void)_XCT_receivedAccessibilityNotification:(int)arg1 withPayload:(id)arg2;
- (void)_XCT_applicationWithBundleID:(id)arg1 didUpdatePID:(int)arg2 andState:(unsigned long long)arg3;
- (id)_IDE_startExecutingTestPlanWithProtocolVersion:(id)arg1;
- (void)runTestConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)runTestSuite:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_checkForTestManager;
- (void)_connectToTestManager;
- (void)_checkManagerDaemonStateAndConnectIfAvailable;
- (void)_resetManagerConnection;
- (void)_connectToIDEWithTransport:(id)arg1;
- (void)_runSuite;
- (void)resumeAppSleep:(id)arg1;
- (id)suspendAppSleep;
- (id)init;

@end
