/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSSet, NSString, NSURL, NSUUID;

@interface XCTestConfiguration : NSObject <NSSecureCoding>
{
    NSURL *_testBundleURL;
    NSSet *_testsToSkip;
    NSSet *_testsToRun;
    _Bool _reportResultsToIDE;
    NSUUID *_sessionIdentifier;
    NSString *_pathToXcodeReportingSocket;
    _Bool _disablePerformanceMetrics;
    _Bool _treatMissingBaselinesAsFailures;
    NSURL *_baselineFileURL;
    NSString *_targetApplicationPath;
    NSString *_targetApplicationBundleID;
    NSString *_productModuleName;
    _Bool _reportActivities;
}

+ (id)configurationWithContentsOfFile:(id)arg1;
+ (id)activeTestConfiguration;
+ (void)setActiveTestConfiguration:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property (atomic, assign) _Bool reportActivities; // @synthesize reportActivities=_reportActivities;
@property (atomic, copy) NSString *productModuleName;
@property (atomic, copy) NSString *targetApplicationBundleID;
@property (atomic, copy) NSString *targetApplicationPath;
@property (atomic, assign) _Bool treatMissingBaselinesAsFailures; // @synthesize treatMissingBaselinesAsFailures=_treatMissingBaselinesAsFailures;
@property (atomic, assign) _Bool disablePerformanceMetrics; // @synthesize disablePerformanceMetrics=_disablePerformanceMetrics;
@property (atomic, assign) _Bool reportResultsToIDE; // @synthesize reportResultsToIDE=_reportResultsToIDE;
@property (atomic, copy) NSURL *baselineFileURL;
@property (atomic, copy) NSString *pathToXcodeReportingSocket;
@property (atomic, copy) NSUUID *sessionIdentifier;
@property (atomic, copy) NSSet *testsToSkip;
@property (atomic, copy) NSSet *testsToRun;
@property (atomic, copy) NSURL *testBundleURL;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (_Bool)writeToFile:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)dealloc;

@end
