/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class XCUIElementQuery;

@protocol XCUIElementTypeQueryProvider
@property (atomic, copy, readonly) XCUIElementQuery *otherElements;
@property (atomic, copy, readonly) XCUIElementQuery *handles;
@property (atomic, copy, readonly) XCUIElementQuery *layoutItems;
@property (atomic, copy, readonly) XCUIElementQuery *layoutAreas;
@property (atomic, copy, readonly) XCUIElementQuery *cells;
@property (atomic, copy, readonly) XCUIElementQuery *levelIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *grids;
@property (atomic, copy, readonly) XCUIElementQuery *rulerMarkers;
@property (atomic, copy, readonly) XCUIElementQuery *rulers;
@property (atomic, copy, readonly) XCUIElementQuery *dockItems;
@property (atomic, copy, readonly) XCUIElementQuery *mattes;
@property (atomic, copy, readonly) XCUIElementQuery *helpTags;
@property (atomic, copy, readonly) XCUIElementQuery *colorWells;
@property (atomic, copy, readonly) XCUIElementQuery *relevanceIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *splitters;
@property (atomic, copy, readonly) XCUIElementQuery *splitGroups;
@property (atomic, copy, readonly) XCUIElementQuery *valueIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *ratingIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *timelines;
@property (atomic, copy, readonly) XCUIElementQuery *tabs;
@property (atomic, copy, readonly) XCUIElementQuery *decrementArrows;
@property (atomic, copy, readonly) XCUIElementQuery *incrementArrows;
@property (atomic, copy, readonly) XCUIElementQuery *steppers;
@property (atomic, copy, readonly) XCUIElementQuery *webViews;
@property (atomic, copy, readonly) XCUIElementQuery *maps;
@property (atomic, copy, readonly) XCUIElementQuery *menuBarItems;
@property (atomic, copy, readonly) XCUIElementQuery *menuBars;
@property (atomic, copy, readonly) XCUIElementQuery *menuItems;
@property (atomic, copy, readonly) XCUIElementQuery *menus;
@property (atomic, copy, readonly) XCUIElementQuery *textViews;
@property (atomic, copy, readonly) XCUIElementQuery *datePickers;
@property (atomic, copy, readonly) XCUIElementQuery *secureTextFields;
@property (atomic, copy, readonly) XCUIElementQuery *textFields;
@property (atomic, copy, readonly) XCUIElementQuery *staticTexts;
@property (atomic, copy, readonly) XCUIElementQuery *scrollBars;
@property (atomic, copy, readonly) XCUIElementQuery *scrollViews;
@property (atomic, copy, readonly) XCUIElementQuery *searchFields;
@property (atomic, copy, readonly) XCUIElementQuery *icons;
@property (atomic, copy, readonly) XCUIElementQuery *images;
@property (atomic, copy, readonly) XCUIElementQuery *links;
@property (atomic, copy, readonly) XCUIElementQuery *toggles;
@property (atomic, copy, readonly) XCUIElementQuery *switches;
@property (atomic, copy, readonly) XCUIElementQuery *pickerWheels;
@property (atomic, copy, readonly) XCUIElementQuery *pickers;
@property (atomic, copy, readonly) XCUIElementQuery *segmentedControls;
@property (atomic, copy, readonly) XCUIElementQuery *activityIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *progressIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *pageIndicators;
@property (atomic, copy, readonly) XCUIElementQuery *sliders;
@property (atomic, copy, readonly) XCUIElementQuery *collectionViews;
@property (atomic, copy, readonly) XCUIElementQuery *browsers;
@property (atomic, copy, readonly) XCUIElementQuery *outlineRows;
@property (atomic, copy, readonly) XCUIElementQuery *outlines;
@property (atomic, copy, readonly) XCUIElementQuery *tableColumns;
@property (atomic, copy, readonly) XCUIElementQuery *tableRows;
@property (atomic, copy, readonly) XCUIElementQuery *tables;
@property (atomic, copy, readonly) XCUIElementQuery *statusBars;
@property (atomic, copy, readonly) XCUIElementQuery *toolbars;
@property (atomic, copy, readonly) XCUIElementQuery *tabGroups;
@property (atomic, copy, readonly) XCUIElementQuery *tabBars;
@property (atomic, copy, readonly) XCUIElementQuery *navigationBars;
@property (atomic, copy, readonly) XCUIElementQuery *keys;
@property (atomic, copy, readonly) XCUIElementQuery *keyboards;
@property (atomic, copy, readonly) XCUIElementQuery *popovers;
@property (atomic, copy, readonly) XCUIElementQuery *toolbarButtons;
@property (atomic, copy, readonly) XCUIElementQuery *menuButtons;
@property (atomic, copy, readonly) XCUIElementQuery *comboBoxes;
@property (atomic, copy, readonly) XCUIElementQuery *popUpButtons;
@property (atomic, copy, readonly) XCUIElementQuery *disclosureTriangles;
@property (atomic, copy, readonly) XCUIElementQuery *checkBoxes;
@property (atomic, copy, readonly) XCUIElementQuery *radioGroups;
@property (atomic, copy, readonly) XCUIElementQuery *radioButtons;
@property (atomic, copy, readonly) XCUIElementQuery *buttons;
@property (atomic, copy, readonly) XCUIElementQuery *dialogs;
@property (atomic, copy, readonly) XCUIElementQuery *alerts;
@property (atomic, copy, readonly) XCUIElementQuery *drawers;
@property (atomic, copy, readonly) XCUIElementQuery *sheets;
@property (atomic, copy, readonly) XCUIElementQuery *windows;
@property (atomic, copy, readonly) XCUIElementQuery *groups;
@end
